twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Resources/fallback_theme': fallback_theme

when@test:
    twig:
        strict_variables: true
